name: Galio Framework
description: Build better apps using React Native
website_url: https://galio.io/
github_url: https://github.com/galio-org/galio
keywords: galio, mobile framework, android react native, ios react native, free mobile framework, react native, free react native, open source react native, mit license, mobile app
twitter_handle: galio
facebook_handle: galio
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji
  - jekyll-admin
