# Site
name: "Blogul TOMbox"
description:
meta_description: "Blogul oficial TOMbox. Afla totul despre moda masculina"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'

baseurl:
google_analytics: 'UA-128434614-1'
disqus: 'demowebsite'
mailchimp-list: 'http://eepurl.com/dPrjHb'

# Authors
authors:
  tombox:
    name: TOMbox
    display_name: TOMbox
    gravatar: assets/images/logo-square.jpg?s=250&d=mm&r=x
    email: tomboxshop@gmail.com
    web: https://www.instagram.com/tomboxshop
    twitter: https://www.instagram.com/tomboxshop
    description: "TOMbox este un brand românesc cu accesorii și seturi bărbătești la cel mai avantajos preț."

  blogatu:
    name: blogatu.ro
    display_name: blogatu.ro
    gravatar: assets/images/blogatu.png?s=250&d=mm&r=x
    email: blogatu@gmail.com
    web: https://www.facebook.com/Blogatu
    twitter: https://twitter.com/blogatu
    description: "Marius Ovidiu Calugaru e numele meu. Insa in mediul online sunt cunoscut drept Blogatu. Si-mi place asta!"

  don:
    name: DON MEN
    display_name: DON MEN
    gravatar: assets/images/don-men.png?s=250&d=mm&r=x
    email: office@don-men.com
    web: https://www.facebook.com/DONMENShopOnline/
    twitter: https://twitter.com/donmenfashion
    description: " Haine in pas cu moda, la preturi accesibile, create special pentru barbatul modern!"




# Plugins
plugins:
  - jekyll-paginate
  - jekyll-archives
  - jekyll-seo-tag

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Pagination
paginate: 6
paginate_path: /page:num/

# Other
markdown: kramdown
highlighter: rouge
